clc
clear all
close all

% Generate rand list

for i=1:60
    rand_or(i,:)=randperm(16);
end

save('Rand_order_movies.mat','rand_or')

n_rep=4;
anno_per_stu=6;

CGlist={'It was incongruent with your standards and ideas',...
'It was unpleasant for you',...
'It violated laws or socially accepted norms',...
'It was unpleasant for somebody else',...
'It was important and relevant for the goals or needs of somebody',...
'The event was uncontrolled',...
'The event was unpredictable',...
'The event occurred suddenly',...
'The event was caused by chance',...
'That was caused by the persons own behavior',...
'That was caused by somebody elses behavior',...
'There was no urgency in the situation',...
'The consequences were predictable',...
'You pressed lips together',...
'You closed your eyes',...
'You had tears in your eyes',...
'You felt your jaw drop',...
'You felt your eyebrows go up',...
'You smiled',...
'You frowned',...
'You opened your eyes widely',...
'You made abrupt body movements',...
'You felt the urge to stop what was happening',...
'You wanted to undo what was happening',...
'You wanted the ongoing situation to last or be repeated',...
'You wanted to oppose someone or something (situation)',...
'You felt motivated to pay attention to what was going on',...
'You felt like tackling the situation and do something',...
'You wanted to be in command of others',...
'You wanted someone to be there to provide help or support',...
'You wanted to move',...
'You wanted to take care of another person or cause',...
'You felt bad',...
'You felt good',...
'You felt strong',...
'You experienced an intense emotional state',...
'You experienced an emotional state for a long time',...
'You felt tired',...
'You felt at ease',...
'You experienced muscle tensions (whole body)',...
'You had a feeling of a lump in the throat',...
'You have stomach cramps',...
'You felt warm',...
'Shivers'};
emolist=[{'fear'}, {'anger'}, {'happiness'}, {'sadness'}, {'satisfaction'}, {'calm'}, {'disgust'}, {'guilt'}, {'love'}, {'contempt'},{'shame'},{'surprise'},{'anxiety'},{'warm-hearted'}];%

totlist=[emolist,CGlist];

n_items=size(totlist,2);
clear rand_or
rand_or=zeros(n_rep,n_items);
rand_or2=cell(40,anno_per_stu);

for stu=1:40
    rand_or_copy=rand_or;
    for i=1:anno_per_stu
        if isempty(find(rand_or==0))
            break
        end
        indexes=find(rand_or_copy==0);
        [row,col]=find(rand_or_copy==0);
        it=randi(size(row,1));
        iter=row(it); item=col(it);
        rand_or2(stu,i)=totlist(item);
        rand_or(iter,item)=stu;
        rand_or_copy(:,item)=1; % avoid same student annotating same item twice
        a=1;
    end
    clear rand_or_copy
end
%Rand_order_items

save('Rand_order_items.mat','rand_or','rand_or2')




